# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import usersubmit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=usersubmit.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default=None, max_length=250, unique=True)),
                ('thumbnail', models.URLField(max_length=1000)),
                ('synopsis', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Review', 'Review'), ('Version', 'Version'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Culture', 'Culture')], max_length=20)),
                ('body', models.TextField(max_length=1000)),
                ('created', models.DateField(null=True)),
                ('published', models.BooleanField(default=True)),
                ('favorited_by_version', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='images',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersubmit.Post'),
        ),
    ]
