# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='images',
            name='body',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
