# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0002_auto_20170830_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
