# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0005_auto_20170830_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersubmit.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
