# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0009_remove_post_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
