# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0010_auto_20170907_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='usersubmit.Post'),
        ),
    ]
