# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersubmit.Post'),
        ),
    ]
