# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersubmit', '0020_auto_20171025_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
