# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
