# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170801_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Review', 'Review'), ('Version', 'Verion'), ('Music', 'Music'), ('Lifestyle', 'Lifestyle')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
